name: "Update Resume Reminder"
title: "Reminder: Update your resume for this quarter"
description: "This issue is automatically created every quarter to remind you to update your resume."
labels: ["resume", "reminder"]

body:
  - type: markdown
    attributes:
      value: |
        ## 📄 Time to update your resume!

        It's time to review your professional achievements and update your resume to reflect your latest work and progress.

        ### Checklist:
        - [ ] Review recent projects or accomplishments
        - [ ] Add new skills or certifications
        - [ ] Update your job history if necessary

        Stay ahead of the curve! 🚀
