name: Generate Resume PDF

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    name: build pdf and upload release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'
          cache: 'yarn'

      # 日本語フォントをインストール (Puppeteer用)
      - name: Install Japanese Fonts
        run: sudo apt-get install -y fonts-noto-cjk

      # 依存パッケージのインストール
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # MarkdownからPDFを生成
      - name: Generate PDF
        run: yarn build:pdf
      
      # PDFファイルをリネーム
      - name: Rename PDF File
        id: rename
        run: |
          DATE=$(date +'%Y%m%d')
          mv ./docs/職務経歴書.pdf ./docs/resume_${DATE}.pdf
          echo "DATE=${DATE}" >> "$GITHUB_OUTPUT"

      # PDF生成後、ファイルの存在確認
      - name: Debug PDF File
        run: |
          ls -l ./docs
          if [ ! -f "./docs/resume_${{ steps.rename.outputs.DATE }}.pdf" ]; then
            echo "Error: Renamed PDF file not found!"
            exit 1
          fi

      # GitHub Releaseの作成
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME=${{ github.ref_name }}
          gh release create "$TAG_NAME" --title "Release $TAG_NAME" --notes "Automated release for $TAG_NAME"

      # PDFアセットをGitHub Releaseにアップロード
      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${{ github.ref_name }}" ./docs/resume_${{ steps.rename.outputs.DATE }}.pdf --clobber