name: Generate Resume PDF

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Volta
        run: |
          curl https://get.volta.sh | bash
          export PATH="$HOME/.volta/bin:$PATH"
          volta install node@22 yarn@4
          echo "PATH=$HOME/.volta/bin:$PATH" >> $GITHUB_ENV
          volta run node --version
          volta run yarn --version

      - name: Install dependencies
        run: volta run yarn install --immutable

      - name: Install dependencies for Puppeteer
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            fonts-noto-cjk \
            libnss3 \
            libatk1.0-0 \
            libatk-bridge2.0-0 \
            libcups2 \
            libxkbcommon-x11-0 \
            libxcomposite1 \
            libxrandr2 \
            libasound2t64 \
            libxss1 \
            libglib2.0-0 \
            libgbm-dev \
            libpangocairo-1.0-0 \
            libpangoft2-1.0-0 \
            libjpeg62 \
            libx11-xcb1

      - name: Generate PDF
        run: volta run yarn build:pdf -- --no-sandbox --disable-setuid-sandbox --disable-dev-shm-usage

      - name: Rename PDF File
        id: rename
        run: |
          DATE=$(date +'%Y%m%d')
          mv ./docs/職務経歴書.pdf ./docs/resume_${DATE}.pdf
          echo "DATE=${DATE}" >> "$GITHUB_OUTPUT"

      - name: Debug PDF File
        run: |
          ls -l ./docs
          if [ ! -f "./docs/resume_${{ steps.rename.outputs.DATE }}.pdf" ]; then
            echo "Error: Renamed PDF file not found!"
            exit 1
          fi

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME=${{ github.ref_name }}
          gh release create "$TAG_NAME" --title "Release $TAG_NAME" --notes "Automated release for $TAG_NAME"

      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${{ github.ref_name }}" ./docs/resume_${{ steps.rename.outputs.DATE }}.pdf --clobber
